### ISSUE TITLE
Mistake in Zend\Barcode documentation

### ISSUE THREAD

**Issue by afilippov1985** [zendframework/zf2-documentation#1366]
http://framework.zend.com/manual/2.3/en/modules/zend.barcode.objects.html#zend-barcode-objects-common-options
`factor` option, actually, has float data type.
See \Zend\Barcode\Object\AbstractObject::setFactor()

Same mistake in ZF1 documentation.

**Comment by froschdesign** [comment]
The same for [`setOrientation`](https://github.com/zendframework/zf2/blob/master/library/Zend/Barcode/Object/AbstractObject.php#L495-499).

**Comment by froschdesign** [comment]
Fixed in ZF1. (zendframework/zf1@51904b64a4f417accf6979b70eac1bc90d281771 and zendframework/zf1@e5c1deb0bb8270f041cca1f650d6d882fbc1ca55)
