### ISSUE TITLE
IsInstanceOf Validator is not documented

### ISSUE THREAD

**Issue by mbn18** [zendframework/zf2-documentation#1437]
we can add example like:

```php
$validator = new \Zend\Validator\IsInstanceOf(array(
    'className' => '\\NameSpace\\Class\\Path', 
));
echo $validator->isValid($anObject);
```
I can also do it but I need to know where? the doc on git is not the same as on the ZF2 site

**Comment by Ocramius** [comment]
Please don't prefix FQCN with `\` when in string context ;-)

Check https://github.com/zendframework/zf2-documentation/tree/master/docs/languages/en/modules

**Comment by mbn18** [comment]
Will follow the best practice of copy paste from others ;)

**Comment by froschdesign** [comment]
Duplicates #942
