### ISSUE TITLE
Ridiculous 404 messages

### ISSUE THREAD

**Issue by atlantic8-web** [zendframework/zf2-documentation#1498]
As an example, go here:
http://framework.zend.com/manual/2.4/en/ref/project.structure.html

Then you see random 404 error messages like:
"We hear Symfony doesn't have this problem" and "NO, Zend Framework is not to blame for this!"

Who's idea was it to add these childish messages???, I think its terrible PR and especially when newcomers to ZF see this, **sigh**

**Comment by froschdesign** [comment]
The 404 error page is not a part of the documentation.
Suggestions and improvements for the website: https://github.com/zendframework/zf-web

This issue can be closed.

**Comment by Ocramius** [comment]
@atlantic8-web regardless of that, it was fun and it is far from childish ;-)

This is a community project, and having fun at building this sort of stuff is vital, or else I wouldn't see a point in doing it (myself) at all.
