### ISSUE TITLE
Part of the text is cut off

### ISSUE THREAD

**Issue by CasperF** [zendframework/zf2-documentation#1500]
In the part about hydrators the text all of a sudden stops. Probably a wrong copy paste or an accidentially remove. Unfortunately I couldn't find the original post regarding the hydrator.

http://framework.zend.com/manual/current/en/in-depth-guide/zend-db-sql-zend-stdlib-hydrator.html#refactoring-hidden-dependencies

**Comment by samsonasik** [comment]
@CasperF , @manuakasam has created PR #1507 for it.

**Comment by CasperF** [comment]
@samsonasik @manuakasam great, thanks for the fix. I had thought it missed a lot of text but apparently it was just the name of the file beneath it, still thanks for clearing it up.
