### ISSUE TITLE
Save association throug ZF2 and cotrain

### ISSUE THREAD

**Issue by ravigupta112** [zendframework/zf2-documentation#1539]
Hi,

Is there any example fo save data multiple into tables using association with the help of ZF2 and doctrine?

**Comment by Ocramius** [comment]
Looks like a cross-post of https://github.com/doctrine/doctrine2/issues/5917. Please ask for help on IRC, the mailing list or stackoverflow first. Also, remember to provide extensive information of what you need, since the question presented here is incomplete and hard to comprehend as-is.
