### ISSUE TITLE
Missing documentation for Zend\Validator\Csrf

### ISSUE THREAD

**Issue by zburnham** [zendframework/zf2-documentation#538]
Csrf is not listed as a standard validator class.

**Comment by GeeH** [comment]
I'm not sure what needs to be added here. The CSRF validator is automatically added to the CSRF element, and isn't designed to be used without the element. The documentation for the CSRF element is pretty good. I'm closing - @zburnham can you provide a use case for CSRF validator without element please? If so, reopen.

**Comment by zburnham** [comment]
I'm a bystander here, I have no idea what this is about :)
