### ISSUE TITLE
Performance section

### ISSUE THREAD

**Issue by ThaDafinser** [zendframework/zf2-documentation#657]
Hello,

in ZF1 there was a performance section, with tips how to improve the performance of the whole framework or components.
http://framework.zend.com/manual/1.12/en/performance.html

This would be also fine for ZF2

**Comment by GeeH** [comment]
Is there any chance of getting all this information as a PR please?

**Comment by ThaDafinser** [comment]
Many points here are already covered ("state of the art") or got invalid, since to much time passed.

So i'm closing this one.
