### ISSUE TITLE
“Learning Dependency Injection” tutorial update

### ISSUE THREAD

**Issue by automatix** [zendframework/zf2-documentation#703]
The "[Learning Dependency Injection](http://framework.zend.com/manual/2.1/en/tutorials/quickstart.di.html)" tutorial should be reviewed and updated, since it references nonexistent classes/methods.

Chapter "[Simplest Usage Case Without Type-hints](http://framework.zend.com/manual/2.1/en/tutorials/quickstart.di.html#simplest-usage-case-without-type-hints)": class `AggregateDefinition`

Chapter "[Simplest usage case (2 classes, one consumes the other)](http://framework.zend.com/manual/2.1/en/tutorials/quickstart.di.html#simplest-usage-case-2-classes-one-consumes-the-other)": method `getInstanceManager()`

**Comment by Martin-P** [comment]
@Ocramius This is already fixed in #708 and #714 and can be closed.
