### ISSUE TITLE
package documentation available but not browsable 

### ISSUE THREAD

**Issue by basz** [zendframework/zf2-documentation#776]
All the zend packages that live in the '\Zend*' namespace do have documentation but aren't indexed...

example
https://zf2.readthedocs.org/en/latest/modules/zendqueue.introduction.html
or
https://zf2.readthedocs.org/en/latest/modules/zendpdf.introduction.html

you can not browser there unless you know the url or search for it.

**Comment by GeeH** [comment]
These packages are deprecated as far as I'm aware, and we shouldn't link to them. If I'm wrong please re-open the issue.
