### ISSUE TITLE
reStructuredText Style Guide

### ISSUE THREAD

**Issue by Ore4444** [zendframework/zf2-documentation#841]
reStructuredText is a flexible markup language. There are many ways to create visually and semantically similar elements. Many different style choices were decided upon migration from the ZF1 docs. The CONTRIBUTING.MD file has a link to the reStructuredText manual, but in my opinion, it's not enough.

It would be very helpful if a Zend representitive will create a minimal style guide, simply outlining the various formatting elements that are used in the docs? This will serve mainly as a reference guide for documentation writers and fixers.

Similar in spirit to: http://alistapart.com/about/style-guide

**Comment by froschdesign** [comment]
No longer needed.
