### ISSUE TITLE
Missing documentation for Escape view helpers

### ISSUE THREAD

**Issue by froschdesign** [zendframework/zf2-documentation#877]
These helpers needs some explanations and examples:
- `Zend\View\Helper\EscapeCss`
- `Zend\View\Helper\EscapeHtml`
- `Zend\View\Helper\EscapeHtmlAttr`
- `Zend\View\Helper\EscapeJs`
- `Zend\View\Helper\EscapeUrl`

There is only a short notice in the [PhpRenderer section](http://framework.zend.com/manual/2.2/en/modules/zend.view.renderer.php-renderer.html#usage).

**Comment by stuartherbert** [comment]
Would be great to see these documented. They're probably the most important View Helpers in the framework.

**Comment by froschdesign** [comment]
This issue has been moved to the [`zend-view`  repository](https://github.com/zendframework/zend-view/issues/99).
