### ISSUE TITLE
Missing documentation for Zend\Validator\Uri

### ISSUE THREAD

**Issue by froschdesign** [zendframework/zf2-documentation#943]
The validator "Uri" needs some explanations and code examples.

https://github.com/zendframework/zf2/blob/master/library/Zend/Validator/Uri.php

**Comment by Sgoettschkes** [comment]
Took me an hour to figure this one out! The new source file is at https://github.com/zendframework/zend-validator/blob/master/src/Uri.php and there is no documentation as of yet!

**Comment by froschdesign** [comment]
Fixed with #1493.
